//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISHT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public Kullanici()
        {
            this.Satis = new HashSet<Satis>();
        }
    
        public int id { get; set; }
        public string adsoyad { get; set; }
        public string kullaniciadi { get; set; }
        public string sifre { get; set; }
        public int yetkiId { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string adres { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public Nullable<bool> silindi { get; set; }
    
        public virtual Yetki Yetki { get; set; }
        public virtual ICollection<Satis> Satis { get; set; }
    }
}
