//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISHT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TShitEntities : DbContext
    {
        public TShitEntities()
            : base("name=TShitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Kullanici> Kullanici { get; set; }
        public DbSet<Satis> Satis { get; set; }
        public DbSet<Urunler> Urunler { get; set; }
        public DbSet<Yetki> Yetki { get; set; }
    }
}
