//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISHT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int satisId { get; set; }
        public int id { get; set; }
        public int urunId { get; set; }
        public System.DateTime tarih { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
