//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISHT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public Urunler()
        {
            this.Satis = new HashSet<Satis>();
        }
    
        public int urunId { get; set; }
        public string urunadi { get; set; }
        public string urunkategori { get; set; }
        public string cinsiyet { get; set; }
        public int adet { get; set; }
        public decimal birimfiyat { get; set; }
        public string beden { get; set; }
        public string resimyolu1 { get; set; }
        public string resimyolu2 { get; set; }
        public string urunbilgisi { get; set; }
        public Nullable<bool> silindi { get; set; }
    
        public virtual ICollection<Satis> Satis { get; set; }
    }
}
